javac Dwarf.java
javac Elf.java
javac EnemyDraw.java
javac Engine.java
javac EngineDraw.java
javac Fellowship.java
javac FellowshipDraw.java
javac Geometry.java
javac GeometryDraw.java
javac GraphicsArea.java
javac Human.java
javac Hobbit.java
javac Main.java
javac MagicRock.java
javac Mountain.java
javac Obstacle.java
javac Player.java
javac PlayerDraw.java
javac PlayingArea.java
javac Position.java
javac Road.java
javac Source.java
javac Tile.java
javac Tower.java
javac TowerDraw.java
javac Writer.java